title: GoBusiness Singapore
url: "https://gobusiness.gov.sg" # the base hostname & protocol for your site, e.g. http://example.com
logo: /images/Gobiz_logo_SG.svg
favicon: /images/Gobiz_favicon.ico
collections:
  contact-us:
    output: true
  run-and-grow:
    output: true
  start-a-business:
    output: true
  licensing-faqs:
    output: true
  business-grants-faqs:
    output: true
  productivity_solutions_grant:
    output: true
  covid-19:
    output: true
  faqs:
    output: true
  covid-faqs:
    output: true
  e-services:
    output: true
  e-services1:
    output: true
  e-services2:
    output: true  
  e-services3:
    output: true
  e-services4:
    output: true
  e-services5:
    output: true   
google_analytics: UA-186826212-1
facebook-pixel: 688926055194344
linkedin-insights: 918155
resources_name: news-and-media


##################################################################################################################
# Everything below this line is Isomer-specific configuration. There should not be a need to edit these settings #
##################################################################################################################
permalink: none
baseurl: ""
exclude: [travis-script.js, .travis.yml, README.md, package.json, package-lock.json, node_modules, vendor/bundle/, vendor/cache/, vendor/gems/, vendor/ruby/, Gemfile, Gemfile.lock]
include: [_redirects]
defaults:
  - scope:
      path: ""
    values:
      layout: "page"
# Custom CSS file path
custom_css_path: "/misc/custom.css"
custom_print_css_path: "/assets/css/print.css"
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
description: test test
